/* eslint-disable */
/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

const triples = {
  'win32-x64-msvc': 'core-native.win32-x64-msvc.node',
}

const key = `${platform}-${arch}-msvc`
const file = triples[key]

if (file) {
  try {
    const localPath = join(__dirname, file)
    if (existsSync(localPath)) {
      nativeBinding = require(localPath)
    }
  } catch (e) {
    loadError = e
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding for ${platform}-${arch}`)
}

module.exports = nativeBinding
