@echo off
REM Cleanup redundant files
REM Generated by project-audit.cjs

mkdir archive\old_roadmaps 2>nul
mkdir archive\backups 2>nul
mkdir archive\test_outputs 2>nul

echo Moving old roadmaps...
move "OLB.md" archive\old_roadmaps\ 2>nul
move "ROADMAP_26w15aC.md" archive\old_roadmaps\ 2>nul
move "ROADMAP_26w15aD.md" archive\old_roadmaps\ 2>nul
move "ROADMAP_26w15aD_FIX.md" archive\old_roadmaps\ 2>nul
move "ROADMAP_26w15aDTest.md" archive\old_roadmaps\ 2>nul
move "ROADMAP_UNIFIED.md" archive\old_roadmaps\ 2>nul
move "P0-P2-DEV-REPORT.md" archive\old_roadmaps\ 2>nul
move "P2_TASKS_PLAN.md" archive\old_roadmaps\ 2>nul
move "PHASE_A2_SUMMARY.md" archive\old_roadmaps\ 2>nul
move "PROGRESS_UPDATE.md" archive\old_roadmaps\ 2>nul
move "SPRINT_12H_PLAN.md" archive\old_roadmaps\ 2>nul
move "SPRINT_12H_PROGRESS.md" archive\old_roadmaps\ 2>nul
move "AUDIT_CHECKLIST.md" archive\old_roadmaps\ 2>nul
move "COMPLETION_CHECKLIST.md" archive\old_roadmaps\ 2>nul
move "DEVELOPMENT_COMPLETION_REPORT.md" archive\old_roadmaps\ 2>nul
move "RELEASE_CHECKLIST.md" archive\old_roadmaps\ 2>nul

echo Removing backup files...
del /s *.bak 2>nul
del /s *.bak2 2>nul
del /s *.old 2>nul

echo Removing test outputs...
del "TEST_SUMMARY.md" 2>nul
del "VERIFICATION_REPORT.md" 2>nul
del "test-complete.cjs" 2>nul
del "test-full-pipeline.cjs" 2>nul
del "test-script-gen.cjs" 2>nul
del "test-ollama.cjs" 2>nul
del "test-simple.cjs" 2>nul
del "DEPLOYMENT_FIX_SUMMARY.md" 2>nul
del "security_audit.json" 2>nul
del "security_audit.log" 2>nul

echo Cleanup complete!
pause
