#!/usr/bin/env node
/**
 * Project Audit and Cleanup Script
 * Analyzes project structure and identifies redundant files
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PROJECT_ROOT = 'D:\\Coding\\OpenOxygen';

// File categories for organization
const FILE_CATEGORIES = {
  // Documentation files to keep
  essentialDocs: [
    'README.md',
    'LICENSE',
    'CHANGELOG.md',
    'PROJECT_STRUCTURE.md',
    'VERSION.txt',
    'RELEASE_NOTES.md'
  ],
  
  // Old/duplicate roadmap files to archive
  oldRoadmaps: [
    '2603141948.md',
    'AgentLOG.md',
    '26w15aB-26w15aHRoadmap.md',
    'OLB.md',
    'ROADMAP_26w15aC.md',
    'ROADMAP_26w15aD.md',
    'ROADMAP_26w15aD_FIX.md',
    'ROADMAP_26w15aDTest.md',
    'ROADMAP_UNIFIED.md',
    'P0-P2-DEV-REPORT.md',
    'P2_TASKS_PLAN.md',
    'PHASE_A2_SUMMARY.md',
    'PROGRESS_UPDATE.md',
    'SPRINT_12H_PLAN.md',
    'SPRINT_12H_PROGRESS.md',
    'AUDIT_CHECKLIST.md',
    'COMPLETION_CHECKLIST.md',
    'DEVELOPMENT_COMPLETION_REPORT.md',
    'RELEASE_CHECKLIST.md'
  ],
  
  // Backup files to remove
  backupPatterns: [
    '*.bak',
    '*.bak2',
    '*.bak3',
    '*.old',
    '*.orig',
    '*~'
  ],
  
  // Test output files
  testOutputs: [
    'TEST_SUMMARY.md',
    'VERIFICATION_REPORT.md',
    'test-complete.cjs',
    'test-full-pipeline.cjs',
    'test-script-gen.cjs',
    'test-ollama.cjs',
    'test-simple.cjs',
    'DEPLOYMENT_FIX_SUMMARY.md',
    'security_audit.json',
    'security_audit.log'
  ],
  
  // Build artifacts
  buildArtifacts: [
    '*.exe',
    '*.msi',
    '*.log'
  ]
};

class ProjectAuditor {
  constructor() {
    this.stats = {
      totalFiles: 0,
      redundantFiles: 0,
      oldRoadmaps: 0,
      backupFiles: 0,
      testOutputs: 0,
      byCategory: {}
    };
    this.redundantFiles = [];
  }
  
  audit() {
    console.log('🔍 Starting Project Audit...\n');
    
    this.scanDirectory(PROJECT_ROOT);
    this.generateReport();
    
    return this.stats;
  }
  
  scanDirectory(dir, relativePath = '') {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relPath = path.join(relativePath, entry.name);
      
      // Skip node_modules, .git, dist
      if (['node_modules', '.git', 'dist', 'target'].includes(entry.name)) {
        continue;
      }
      
      if (entry.isDirectory()) {
        this.scanDirectory(fullPath, relPath);
      } else {
        this.analyzeFile(fullPath, relPath, entry.name);
      }
    }
  }
  
  analyzeFile(fullPath, relPath, fileName) {
    this.stats.totalFiles++;
    
    // Check for backup files
    if (this.isBackupFile(fileName)) {
      this.stats.backupFiles++;
      this.redundantFiles.push({ type: 'backup', path: relPath });
      return;
    }
    
    // Check for old roadmaps
    if (FILE_CATEGORIES.oldRoadmaps.includes(fileName)) {
      this.stats.oldRoadmaps++;
      this.redundantFiles.push({ type: 'oldRoadmap', path: relPath });
      return;
    }
    
    // Check for test outputs
    if (FILE_CATEGORIES.testOutputs.includes(fileName)) {
      this.stats.testOutputs++;
      this.redundantFiles.push({ type: 'testOutput', path: relPath });
      return;
    }
    
    // Categorize by extension
    const ext = path.extname(fileName).toLowerCase();
    this.stats.byCategory[ext] = (this.stats.byCategory[ext] || 0) + 1;
  }
  
  isBackupFile(fileName) {
    return FILE_CATEGORIES.backupPatterns.some(pattern => {
      const regex = new RegExp(pattern.replace('*', '.*') + '$');
      return regex.test(fileName);
    });
  }
  
  generateReport() {
    this.stats.redundantFiles = this.redundantFiles.length;
    
    console.log('📊 Audit Results:\n');
    console.log(`Total files scanned: ${this.stats.totalFiles}`);
    console.log(`Redundant files found: ${this.stats.redundantFiles}`);
    console.log(`  - Old roadmaps: ${this.stats.oldRoadmaps}`);
    console.log(`  - Backup files: ${this.stats.backupFiles}`);
    console.log(`  - Test outputs: ${this.stats.testOutputs}`);
    console.log('\n📁 Files by category:');
    
    Object.entries(this.stats.byCategory)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .forEach(([ext, count]) => {
        console.log(`  ${ext || '(no ext)'}: ${count}`);
      });
    
    console.log('\n🗑️  Redundant files to clean:');
    this.redundantFiles.slice(0, 20).forEach(file => {
      console.log(`  [${file.type}] ${file.path}`);
    });
    
    if (this.redundantFiles.length > 20) {
      console.log(`  ... and ${this.redundantFiles.length - 20} more`);
    }
  }
  
  createCleanupScript() {
    const scriptPath = path.join(PROJECT_ROOT, 'scripts', 'cleanup-redundant.bat');
    
    let script = '@echo off\n';
    script += 'REM Cleanup redundant files\n';
    script += 'REM Generated by project-audit.cjs\n\n';
    script += 'mkdir archive\\old_roadmaps 2>nul\n';
    script += 'mkdir archive\\backups 2>nul\n';
    script += 'mkdir archive\\test_outputs 2>nul\n\n';
    
    // Move old roadmaps
    script += 'echo Moving old roadmaps...\n';
    FILE_CATEGORIES.oldRoadmaps.forEach(file => {
      if (fs.existsSync(path.join(PROJECT_ROOT, file))) {
        script += `move "${file}" archive\\old_roadmaps\\ 2>nul\n`;
      }
    });
    
    // Remove backup files
    script += '\necho Removing backup files...\n';
    script += 'del /s *.bak 2>nul\n';
    script += 'del /s *.bak2 2>nul\n';
    script += 'del /s *.old 2>nul\n';
    
    // Remove test outputs
    script += '\necho Removing test outputs...\n';
    FILE_CATEGORIES.testOutputs.forEach(file => {
      script += `del "${file}" 2>nul\n`;
    });
    
    script += '\necho Cleanup complete!\n';
    script += 'pause\n';
    
    fs.writeFileSync(scriptPath, script);
    console.log(`\n✅ Cleanup script created: ${scriptPath}`);
  }
}

// Run audit
const auditor = new ProjectAuditor();
auditor.audit();
auditor.createCleanupScript();

console.log('\n🔧 Next steps:');
console.log('1. Review audit results');
console.log('2. Run scripts/cleanup-redundant.bat to clean files');
console.log('3. Organize remaining files by category');
console.log('4. Update .gitignore if needed');
